version: '3'

networks:
  mindstack:

services:
  js_registry:
    image: verdaccio/verdaccio
    container_name: mindstack_registry--js
    networks:
      - mindstack
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    # volumes:
    #   - "./storage:/verdaccio/storage"
    #   - "./config:/verdaccio/conf"
    #   - "./plugins:/verdaccio/plugins"
  # rasa:
  #   build:
  #       context: .
  #       dockerfile: ./docker/rasa/Dockerfile
  #
  #   container_name: mindstack_rasa
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./projects:/app/projects
  #   networks:
  #     - mindstack
  # core:
  #   build:
  #       context: .
  #       dockerfile: ./docker/nodejs/Dockerfile
  #   container_name: mindstack_core
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./code:/code
  #   networks:
  #     - mindstack
