version: '3'

networks:
  mindstack:

services:
  rasa:
    build:
        context: .
        dockerfile: ./docker/rasa/Dockerfile

    container_name: mindstack_rasa
    ports:
      - "5000:5000"
    volumes:
      - ./projects:/app/projects
    networks:
      - mindstack
  # core:
  #   build:
  #       context: .
  #       dockerfile: ./docker/nodejs/Dockerfile
  #   container_name: mindstack_core
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./code:/code
  #   networks:
  #     - mindstack
